### SERVICE ###

apiVersion: v1
kind: Service
metadata:
  name: mortgage-repayment-app-service
spec:
  selector:
    app: mortgage-repayment-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
